### ISSUE TITLE
Aren't you planning to extend this project to Arduino family like Arduino Nano?

### ISSUE THREAD

**Issue by FleXoft** [smittytone/Depot#1]
https://store.arduino.cc/products/arduino-nano

**Comment by smittytone** [comment]
Not in the near term, I’m afraid. It _could_ happen in future, but there’s so much more functionality to add to the RP2040 implementation before I’d consider supporting a completely different MCU and SDK.

**Comment by smittytone** [comment]
Might have a look at adding this, though: https://store.arduino.cc/collections/nano-family/products/arduino-nano-rp2040-connect

**Comment by FleXoft** [comment]
Ok. Thanks for the quick response.
